import { ThemeConfig, ThemeName } from './types'

export const themes: Record<ThemeName, ThemeConfig> = {
  linear: {
    name: 'linear',
    displayName: 'Linear',
    description: 'Minimal Tech - Ultra clean, much whitespace',
    colors: {
      background: '#ffffff',
      foreground: '#0a0a0a',
      primary: '#5e6ad2',
      accent: '#5e6ad2',
      muted: '#fafafa',
      border: '#e5e5e5',
      inputBg: '#ffffff',
      inputBorder: '#e5e5e5',
      buttonBg: '#0a0a0a',
      buttonText: '#ffffff',
      buttonHover: '#262626',
      success: '#10b981',
      error: '#ef4444',
    },
    typography: {
      fontFamily: {
        heading: 'var(--font-geist-sans)',
        body: 'var(--font-geist-sans)',
        mono: 'var(--font-geist-mono)',
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '3.75rem',
        '7xl': '4.5rem',
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
    },
    layout: {
      containerMaxWidth: '1200px',
      spacing: {
        tight: '0.5rem',
        normal: '1rem',
        loose: '2rem',
      },
      borderRadius: {
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
    },
    animations: {
      transitions: 'all 0.2s ease',
      duration: {
        fast: '150ms',
        normal: '200ms',
        slow: '300ms',
      },
      effects: ['smooth', 'subtle'],
    },
    classes: {
      container: 'bg-white text-zinc-900',
      heading: 'font-geist-sans font-semibold text-zinc-900',
      body: 'font-geist-sans text-zinc-600',
      button: 'bg-zinc-900 text-white hover:bg-zinc-800 rounded-lg transition-all',
      buttonPrimary: 'bg-zinc-900 text-white hover:bg-zinc-800',
      buttonSecondary: 'bg-white border border-zinc-200 text-zinc-900 hover:bg-zinc-50',
      input: 'bg-white border border-zinc-200 text-zinc-900 placeholder:text-zinc-400 rounded-lg',
      card: 'bg-white border border-zinc-200 rounded-lg',
      badge: 'bg-zinc-100 text-zinc-700 rounded-full',
    },
  },
  stripe: {
    name: 'stripe',
    displayName: 'Stripe',
    description: 'Premium Bold - Gradients, purple/blue',
    colors: {
      background: '#0a0e27',
      foreground: '#ffffff',
      primary: '#635bff',
      secondary: '#7c3aed',
      accent: '#8b5cf6',
      muted: '#1e293b',
      border: '#334155',
      inputBg: '#1e293b',
      inputBorder: '#334155',
      buttonBg: '#635bff',
      buttonText: '#ffffff',
      buttonHover: '#7c3aed',
      success: '#10b981',
      error: '#ef4444',
    },
    typography: {
      fontFamily: {
        heading: 'var(--font-geist-sans)',
        body: 'var(--font-geist-sans)',
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '3.75rem',
        '7xl': '4.5rem',
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
    },
    layout: {
      containerMaxWidth: '1200px',
      spacing: {
        tight: '0.5rem',
        normal: '1rem',
        loose: '2rem',
      },
      borderRadius: {
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
    },
    animations: {
      transitions: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      duration: {
        fast: '150ms',
        normal: '300ms',
        slow: '500ms',
      },
      effects: ['smooth', 'parallax', 'reveal'],
    },
    classes: {
      container: 'bg-[#0a0e27] text-white',
      heading: 'font-geist-sans font-bold text-white bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent',
      body: 'font-geist-sans text-slate-300',
      button: 'bg-gradient-to-r from-purple-600 to-blue-600 text-white hover:from-purple-700 hover:to-blue-700 rounded-lg transition-all shadow-lg',
      buttonPrimary: 'bg-gradient-to-r from-purple-600 to-blue-600 text-white hover:from-purple-700 hover:to-blue-700',
      buttonSecondary: 'bg-slate-800 border border-slate-700 text-white hover:bg-slate-700',
      input: 'bg-slate-800 border border-slate-700 text-white placeholder:text-slate-400 rounded-lg',
      card: 'bg-slate-800/50 border border-slate-700 rounded-lg backdrop-blur-sm',
      badge: 'bg-purple-500/20 text-purple-300 border border-purple-500/30 rounded-full',
    },
  },
  notion: {
    name: 'notion',
    displayName: 'Notion',
    description: 'Playful & Warm - Beige/cream, rounded corners',
    colors: {
      background: '#f7f6f3',
      foreground: '#37352f',
      primary: '#2383e2',
      accent: '#e16259',
      muted: '#f1f1ef',
      border: '#e9e9e7',
      inputBg: '#ffffff',
      inputBorder: '#e9e9e7',
      buttonBg: '#2383e2',
      buttonText: '#ffffff',
      buttonHover: '#1a6bc7',
      success: '#0f7b0f',
      error: '#e16259',
    },
    typography: {
      fontFamily: {
        heading: 'var(--font-geist-sans)',
        body: 'var(--font-geist-sans)',
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '3.75rem',
        '7xl': '4.5rem',
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
    },
    layout: {
      containerMaxWidth: '1200px',
      spacing: {
        tight: '0.5rem',
        normal: '1rem',
        loose: '2rem',
      },
      borderRadius: {
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.25rem',
        full: '9999px',
      },
    },
    animations: {
      transitions: 'all 0.2s cubic-bezier(0.34, 1.56, 0.64, 1)',
      duration: {
        fast: '150ms',
        normal: '200ms',
        slow: '400ms',
      },
      effects: ['bouncy', 'playful'],
    },
    classes: {
      container: 'bg-[#f7f6f3] text-[#37352f]',
      heading: 'font-geist-sans font-bold text-[#37352f]',
      body: 'font-geist-sans text-[#787774]',
      button: 'bg-[#2383e2] text-white hover:bg-[#1a6bc7] rounded-xl transition-all shadow-sm hover:shadow-md hover:scale-105',
      buttonPrimary: 'bg-[#2383e2] text-white hover:bg-[#1a6bc7] rounded-xl',
      buttonSecondary: 'bg-white border border-[#e9e9e7] text-[#37352f] hover:bg-[#f1f1ef] rounded-xl',
      input: 'bg-white border border-[#e9e9e7] text-[#37352f] placeholder:text-[#9b9a97] rounded-xl',
      card: 'bg-white border border-[#e9e9e7] rounded-xl shadow-sm',
      badge: 'bg-[#f1f1ef] text-[#37352f] rounded-full',
    },
  },
  apple: {
    name: 'apple',
    displayName: 'Apple',
    description: 'Luxury Minimal - Black, white, one accent',
    colors: {
      background: '#000000',
      foreground: '#ffffff',
      primary: '#0071e3',
      accent: '#0071e3',
      muted: '#1d1d1f',
      border: '#424245',
      inputBg: '#1d1d1f',
      inputBorder: '#424245',
      buttonBg: '#0071e3',
      buttonText: '#ffffff',
      buttonHover: '#0077ed',
      success: '#30d158',
      error: '#ff3b30',
    },
    typography: {
      fontFamily: {
        heading: 'var(--font-geist-sans)',
        body: 'var(--font-geist-sans)',
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '3.75rem',
        '7xl': '4.5rem',
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
    },
    layout: {
      containerMaxWidth: '1400px',
      spacing: {
        tight: '0.5rem',
        normal: '1.5rem',
        loose: '3rem',
      },
      borderRadius: {
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
    animations: {
      transitions: 'all 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
      duration: {
        fast: '200ms',
        normal: '400ms',
        slow: '600ms',
      },
      effects: ['reveal', 'elegant', 'scroll'],
    },
    classes: {
      container: 'bg-black text-white',
      heading: 'font-geist-sans font-semibold text-white',
      body: 'font-geist-sans text-neutral-400',
      button: 'bg-[#0071e3] text-white hover:bg-[#0077ed] rounded-full transition-all',
      buttonPrimary: 'bg-[#0071e3] text-white hover:bg-[#0077ed] rounded-full',
      buttonSecondary: 'bg-neutral-800 border border-neutral-700 text-white hover:bg-neutral-700 rounded-full',
      input: 'bg-neutral-900 border border-neutral-800 text-white placeholder:text-neutral-500 rounded-full',
      card: 'bg-neutral-900 border border-neutral-800 rounded-2xl',
      badge: 'bg-neutral-800 text-neutral-300 border border-neutral-700 rounded-full',
    },
  },
  brutalist: {
    name: 'brutalist',
    displayName: 'Brutalist',
    description: 'Raw & Edgy - Hard borders, high contrast',
    colors: {
      background: '#ffffff',
      foreground: '#000000',
      primary: '#ffff00',
      accent: '#ffff00',
      muted: '#f5f5f5',
      border: '#000000',
      inputBg: '#ffffff',
      inputBorder: '#000000',
      buttonBg: '#000000',
      buttonText: '#ffff00',
      buttonHover: '#333333',
      success: '#00ff00',
      error: '#ff0000',
    },
    typography: {
      fontFamily: {
        heading: 'var(--font-space-mono)',
        body: 'var(--font-space-mono)',
        mono: 'var(--font-space-mono)',
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '3.75rem',
        '7xl': '4.5rem',
      },
      fontWeight: {
        normal: '400',
        medium: '700',
        semibold: '700',
        bold: '900',
      },
    },
    layout: {
      containerMaxWidth: '1200px',
      spacing: {
        tight: '0.5rem',
        normal: '1rem',
        loose: '2rem',
      },
      borderRadius: {
        sm: '0',
        md: '0',
        lg: '0',
        xl: '0',
        full: '0',
      },
    },
    animations: {
      transitions: 'none',
      duration: {
        fast: '0ms',
        normal: '0ms',
        slow: '0ms',
      },
      effects: ['none', 'glitchy'],
    },
    classes: {
      container: 'bg-white text-black border-4 border-black',
      heading: 'font-space-mono font-black text-black uppercase',
      body: 'font-space-mono text-black',
      button: 'bg-black text-yellow-400 hover:bg-gray-900 border-4 border-black uppercase font-bold transition-none',
      buttonPrimary: 'bg-black text-yellow-400 border-4 border-black uppercase font-bold',
      buttonSecondary: 'bg-white border-4 border-black text-black hover:bg-gray-100 uppercase font-bold',
      input: 'bg-white border-4 border-black text-black placeholder:text-gray-500 uppercase font-mono',
      card: 'bg-white border-4 border-black',
      badge: 'bg-yellow-400 text-black border-2 border-black uppercase font-bold',
    },
  },
  webflow: {
    name: 'webflow',
    displayName: 'Webflow',
    description: 'Modern Agency - Glass morphism, vibrant gradients',
    colors: {
      background: '#0a0a0a',
      foreground: '#ffffff',
      primary: '#4353ff',
      secondary: '#ff006e',
      accent: '#00f5ff',
      muted: '#1a1a1a',
      border: '#2a2a2a',
      inputBg: 'rgba(255, 255, 255, 0.05)',
      inputBorder: 'rgba(255, 255, 255, 0.1)',
      buttonBg: '#4353ff',
      buttonText: '#ffffff',
      buttonHover: '#5c6cff',
      success: '#00ff88',
      error: '#ff006e',
    },
    typography: {
      fontFamily: {
        heading: 'var(--font-geist-sans)',
        body: 'var(--font-geist-sans)',
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '3.75rem',
        '7xl': '4.5rem',
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
    },
    layout: {
      containerMaxWidth: '1400px',
      spacing: {
        tight: '0.5rem',
        normal: '1rem',
        loose: '2rem',
      },
      borderRadius: {
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
    animations: {
      transitions: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      duration: {
        fast: '150ms',
        normal: '300ms',
        slow: '500ms',
      },
      effects: ['scroll-triggered', '3d-transforms', 'glass'],
    },
    classes: {
      container: 'bg-zinc-950 text-white',
      heading: 'font-geist-sans font-bold text-white bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400 bg-clip-text text-transparent',
      body: 'font-geist-sans text-zinc-300',
      button: 'bg-gradient-to-r from-blue-600 to-purple-600 text-white hover:from-blue-700 hover:to-purple-700 rounded-xl transition-all shadow-lg backdrop-blur-sm',
      buttonPrimary: 'bg-gradient-to-r from-blue-600 to-purple-600 text-white hover:from-blue-700 hover:to-purple-700 rounded-xl',
      buttonSecondary: 'bg-white/10 border border-white/20 text-white hover:bg-white/20 backdrop-blur-md rounded-xl',
      input: 'bg-white/5 border border-white/10 text-white placeholder:text-zinc-400 backdrop-blur-md rounded-xl',
      card: 'bg-white/5 border border-white/10 backdrop-blur-md rounded-xl',
      badge: 'bg-gradient-to-r from-blue-500/20 to-purple-500/20 text-blue-300 border border-blue-500/30 rounded-full backdrop-blur-sm',
    },
  },
}

// Helper para obtener un tema
export function getTheme(themeName: ThemeName): ThemeConfig {
  return themes[themeName] || themes.linear
}

// Helper para obtener todos los temas disponibles
export function getAllThemes(): ThemeConfig[] {
  return Object.values(themes)
}

// Helper para validar si un tema existe
export function isValidTheme(themeName: string): themeName is ThemeName {
  return themeName in themes
}

